#!/bin/bash
VAPI_KEY=$(grep VAPI_API_KEY /Users/opoclaw1/claudeclaw/.env | cut -d= -f2)
TODAY=$(date '+%Y-%m-%d')
WEEKDAY=$(date '+%A')

curl -s -X PATCH "https://api.vapi.ai/assistant/b12b30d9-a75b-48de-a19b-b494e1eaa1a3" \
  -H "Authorization: Bearer $VAPI_KEY" \
  -H "Content-Type: application/json" \
  -d "{\"model\":{\"provider\":\"openai\",\"model\":\"gpt-4o-mini\",\"messages\":[{\"role\":\"system\",\"content\":\"Eres Thorn, el asistente personal de Gonzalo Estrada. COO de OpoClaw. Chill, directo, hablas como persona real. Sin emojis. Sin frases de AI. Sin adulacion. Vas al punto. Espanol natural.\n\nFECHA DE HOY: $TODAY ($WEEKDAY). Usa esta fecha como referencia para calcular 'manana', 'el viernes', etc. Siempre agenda en el futuro.\n\nTienes tools: check_calendar (calendario), create_event (crear eventos en Google Calendar), create_task (tareas), save_note (notas), web_search (internet). Usaias silenciosamente y habla el resultado.\"}],\"maxTokens\":150,\"tools\":[{\"type\":\"function\",\"function\":{\"name\":\"check_calendar\",\"description\":\"Revisa calendario hoy y manana\",\"parameters\":{\"type\":\"object\",\"properties\":{},\"required\":[]}},\"server\":{\"url\":\"https://keisha-inescapable-clavately.ngrok-free.dev/api/vapi\"}},{\"type\":\"function\",\"function\":{\"name\":\"create_event\",\"description\":\"Agrega evento al Google Calendar\",\"parameters\":{\"type\":\"object\",\"properties\":{\"title\":{\"type\":\"string\"},\"date\":{\"type\":\"string\",\"description\":\"YYYY-MM-DD\"},\"time\":{\"type\":\"string\",\"description\":\"HH:MM 24h\"},\"duration\":{\"type\":\"string\"},\"description\":{\"type\":\"string\"}},\"required\":[\"title\",\"date\"]}},\"server\":{\"url\":\"https://keisha-inescapable-clavately.ngrok-free.dev/api/vapi\"}},{\"type\":\"function\",\"function\":{\"name\":\"create_task\",\"description\":\"Crea tarea\",\"parameters\":{\"type\":\"object\",\"properties\":{\"title\":{\"type\":\"string\"},\"description\":{\"type\":\"string\"}},\"required\":[\"title\"]}},\"server\":{\"url\":\"https://keisha-inescapable-clavately.ngrok-free.dev/api/vapi\"}},{\"type\":\"function\",\"function\":{\"name\":\"save_note\",\"description\":\"Guarda nota\",\"parameters\":{\"type\":\"object\",\"properties\":{\"content\":{\"type\":\"string\"},\"title\":{\"type\":\"string\"}},\"required\":[\"content\"]}},\"server\":{\"url\":\"https://keisha-inescapable-clavately.ngrok-free.dev/api/vapi\"}},{\"type\":\"function\",\"function\":{\"name\":\"web_search\",\"description\":\"Busca en internet\",\"parameters\":{\"type\":\"object\",\"properties\":{\"query\":{\"type\":\"string\"}},\"required\":[\"query\"]}},\"server\":{\"url\":\"https://keisha-inescapable-clavately.ngrok-free.dev/api/vapi\"}}]}}" > /dev/null
